[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
log = "0.4.17"

[dependencies.rocket_db_pools]
version = "0.1.0-rc.2"
features = ["deadpool_postgres"]
