import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Producer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <div className={styles.logoContainer}>
            <Image height="32" width="32" src="/" alt="logo" />
            <p>Food placeholder</p>
          </div>
          <div className={styles.menuContainer}>
            <a>aaa</a> <a>aaa</a> <a>aaa</a> <a>aaa</a>
          </div>
        </header>
      </main>
    </>
  );
}
